spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://146.56.190.175:3306/menu?serverTimezone=UTC&characterEncoding=UTF-8
    username: musinsa
    password: 1234
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        default_batch_fetch_size: 100

server:
  error:
    include-stacktrace: never
  port: 8888

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
